language: ruby
cache: bundler

bundler_args: --without=development

before_install:
  # Install Bundler v2 as Travis still uses v1.x
  - gem update --system
  - gem install bundler

rvm:
  - 2.6.0
  - 2.3.8
